### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by scriptzteam** [cyborg0922/bchpusher#2]
```
##:~/bchpusher/bchpusher# python3

Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitcash, bchpusher
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/bchpusher/bchpusher/bchpusher.py", line 3, in <module>
    from bchpusher import memo
ImportError: cannot import name 'memo'
```

**Comment by AustEcon** [comment]
Yeah. Sorry. Have had this on the back burner while I worked on pull requests for bitcash (which this module requires to work how I want it to). Was originally using this from within bitcash for easy testing... have not been bothered to fix imports because didn't have changes to bitcash just yet. But I do now :)
- I'll fix this soon - easy fix! Sorry.

**Comment by scriptzteam** [comment]
Thank you :)

**Comment by AustEcon** [comment]
See my latest commit: "fixed imports, added op_pushdata_codes, fee=2 (temporary)"
- if you throw the bchpusher folder into your python Lib/site packages folder... should work alright now :)
- I don't think I'll have a pip3 installer for this for a while... so copy and paste will have to do for now.
- I've been working on fixing fee calculation on bitcash... https://github.com/sporestack/bitcash/pull/20
- Now accurate for plain messages to 1sat/byte... just need to fix it for custom_pushdata now (which bchpusher uses) - until then need to use bchpusher with 2 sat / byte.

I've only run some very sporadic test txns with fee=2 and seems to work okay. Still early days I'm afraid... Thanks for the heads up!
If you find other issues don't hesitate to post again :) Cheers!

**Comment by scriptzteam** [comment]
Now i getting those:

```
##~/bchpusher/bchpusher# python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitcash, bchpusher
>>> my_key = bitcash.PrivateKey("blaaaaaaaaaaah")
>>> bchpusher.bchpush(my_key, [('6d02', 'hex'), ('TEST', 'utf-8')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'bchpusher' has no attribute 'bchpush'
```

**Comment by AustEcon** [comment]
Ahh!! Thank you! It's because I've called it bchpush in the readme... But it's still called bitpush in the code. 

Replace "bchpush" with "bitpush". Should work :)

Let me know how it goes. 

If you use ipython notebook it let's you tab through all the functions in a module and read the docstrings as you go...

I'm sleeping now so won't be able to help for like 10 more hours

**Comment by scriptzteam** [comment]
I tried and  xD

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/bchpusher/bchpusher/bchpusher.py", line 132, in bitpush
    rawtx = PrivateKey.create_transaction([], fee=fee, message=pushdata, custom_pushdata=True)
TypeError: create_transaction() got an unexpected keyword argument 'custom_pushdata'
```

**Comment by ghost** [comment]
You'll need to install from the git version or bitcash or wait till I release a new version on pip. Hopefully the new version will come soon :).

**Comment by scriptzteam** [comment]
@teran-mckinney i did tried that from git ;)

**Comment by AustEcon** [comment]
What I'm doing at the moment is just a basic git clone and then have the latest bitcash folder copied over the old bitcash folder in Lib/site-packages.

If you don't want to mess around with your main install you could make a virtual environment.

It works for me with either of these two setups (either everything on main install or everything within an activated venv). Gotta make sure you don't have the whole repo in there... Just the bitcash folder.

PS: probably what you're doing is downloading the latest "release" of bitcash... but teran-mckinney hasn't done a new release yet. We've been making a lot of changes... 

you'll have to git clone and then copy paste to get the newest changes

**Comment by scriptzteam** [comment]
So do i copy everything there in those paths?

```
>>> import site; site.getsitepackages()
['/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']
```

**Comment by AustEcon** [comment]
I've just changed bitpush --> bchpush...
Um... I will see what the path is on my ubuntu virtualbox... and what steps I do... 1 sec

**Comment by scriptzteam** [comment]
its posting now the tx :)

but all getting rejected as unknown tx after a while on bitcoin.com explorer?

**Comment by scriptzteam** [comment]
Memo.cash posting input as 0.00012603 bch
Your script as 0.00189421 bch

Thats so much difference why?

**Comment by AustEcon** [comment]
Hmmm. What is the fee in sat/byte on the block explorer? is it >1 sat / byte?

**Comment by scriptzteam** [comment]
Sample in usd and bch:

bch image - https://i.imgur.com/MAnGUB5.png

```
Inputs & Outputs:
1.38 usd
1.37 usd
< 0.01 usd
< 0.01 usd


Inputs & Outputs:
0.00189421 bch
0.00189229 bch
0.00000192 bch
0.88 Satoshi

```

**Comment by AustEcon** [comment]
Yeah... if you add in an argument to bchpush of fee = 2 or fee = 3... it will work.

`bchpusher.bchpush(my_key, [('6d01', 'hex'), ('new_name', 'utf-8')], fee=3) `

This works for me. 
Sorry about this! I know how frustrating this kind of thing can be!
I thought I fixed this by increasing the default to 2... and I did... but only for memo and blockpress. Forgot to do it for the main event! 

Thanks for catching this and persisting with it... I will change the default to like 3 sat / byte until I have completed all of the fixes on bitcash for fee calculation. (I fixed it for plain messages but 1 sat/byte still will not work with more customised pushdata...)

Let me know when you have success... You'll probably need to do a CPFP now for the other transactions you've got sitting there now... sorry (you can use electron cash wallet for that.. just right click and do child pays for parent) - in case you didn't already know that.

PS: My setup is a virtual environment with the bitcash and bchpusher sitting in lib/python3.6/site-packages (sounds like you've got that part working now though)

**Comment by scriptzteam** [comment]
fees=3 still wont pass it, says after a while tx not found

https://i.imgur.com/xPgSAns.png

**Comment by AustEcon** [comment]
hmm. mine works with higher fee on a fresh wallet (without txns stuck in mempool).
- Have you tried with a fresh wallet?
- I think you'll have to go through each transaction and clear them from the mempool on electron cash now with CPFP... so sorry. 
- I think once you've sent one with <1 sat/byte - all the other subsequent ones don't go through anymore because they're dependent on this same UTXO (which is now stuck).

https://explorer.bitcoin.com/bch/tx/bb107fff367407bb4e7c0badd25c917285caa4777dd5b6a6da4b2ff58ebd7fb0

**Comment by scriptzteam** [comment]
hmm so i am foked up :D

so make new wallet and set fee=3 will help? or? :D

**Comment by AustEcon** [comment]
It is working for me with fee = 3. Should work. 
Or CPFP on your current slew of stuck transactions and will clear with next block...you'll probably want to do that aswell anyway.

**Comment by scriptzteam** [comment]
Will it stuck forever? nope right or?

**Comment by AustEcon** [comment]
Nah it clears from mempool eventually but takes ages. If you do child pays for parent on the stuck UTXOs (like do a 3 sat / byte CPFP)... they will all miraculously clear in the next block :)
- Just use electron cash. Right click on the transaction --> CPFP

Please tell me when / if it it is working.

**Comment by scriptzteam** [comment]
umm on electron cash when i click on history transacions then on tx there in no option for CPFP

**Comment by AustEcon** [comment]
There won't be an option for all of them. Try them all. Eventually one of them will show an option.
Give it a good waking 10 sat/byte to be sure

**Comment by scriptzteam** [comment]
Will there be other solution for it anytime soon? it happens even with fee=3 and new created wallet, i post about 10 at once and all gone ...

**Comment by AustEcon** [comment]
That has me stumped then. Works for me with latest bchpusher and bitcash copied in.
Fee = 3 sat/byte.
**Are the transactions confirming**? If they're not confirming then there is still a chain of stuck txns that need to be cleared first.

Yes. There will be a fix for calculating the correct fee soon. :)

**Comment by scriptzteam** [comment]
How to clear them now? :D ^^

https://i.imgur.com/3VYg2Dy.png

**Comment by AustEcon** [comment]
I don't know. Probably not a good idea to keep spamming though if its not working. If you spam out loads of transactions that have fee too low... it becomes harder and harder to do an adequate CPFP to remedy the situation... If you've gone through and done CPFP (with high fee) on enough of the transactions then most or all should clear with next block... I can't help beyond this.

I don't know why it wouldn't work with a fresh wallet unless you've transferred these same "stuck" UTXOs to the new "fresh" wallet... in which case it actually wasn't a fresh wallet that you used?

I've always been able to get myself back to a "clean" wallet after having mishaps like this with CPFP. You reach a point where it all "clicks" at the next block and like 10 transactions all confirm at once.

**Comment by AustEcon** [comment]
@scriptzteam So I've been having a bit of a play around. I have now fully fixed fee calculation on my feature branch of bitcash called "accurate_fee_calculation_custom_pushdata" and submitted a pull request to @teran-mckinney 

~~To be honest, I am actually getting a bit of hit and miss here and there - which I think happens when you try to send the **same exact thing twice in quick succession** - I think the network perceives this as an attempted double spend or something (which it kinda is)... And after you have committed such an offense... you are in a kind of "sin bin" for a while until next confirmation... or that is what it seems like to me (MAYBE - I don't know for sure).~~

But once I got all my ducks in a row and just did one careful transaction at a time (changing the message each and every time... I can continue spending again and again with the same unconfirmed UTXO and I have no issues at all)...

**Comment by ghost** [comment]
> To be honest, I am actually getting a bit of hit and miss here and there - which I think happens when you try to send the same exact thing twice in quick succession

Is the TXID the same or are the inputs the same?

**Comment by AustEcon** [comment]
Well I just did a 3 x "hello" spam test (with hex prefix for memo.cash changing name)... works beautifully :) 
- 3 different transaction ids. 
- All routed no problem at exactly 1 sat/byte
- I can only assume that I was having a hangover from routing payments at <1 sat/byte... when that happens it is really not a good experience! If I was trying to double spend, Bitcash throws an error anyway! (so I'm obviously mistaken)

I think that all of these issues should be solved now for @scriptzteam if he downloads the latest version of bitcash and bchpusher... Shame he's had so many issues... I didn't expect anyone to be even using bchpusher yet...

If that still doesn't work will just have to wait for official releases.
